### ISSUE TITLE
Converting to the G'MIC language 

### ISSUE THREAD

**Issue by myselfhimself** [weightan/SchrodingerWellPython#1]
Hello,
per Reptorian's request, translation of this project's algorithm is slowly starting for the G'MIC language.

This is being dealt with in [this pixls.us topic](https://discuss.pixls.us/t/looking-for-a-gmic-python-scripter-to-help-me-out-here/24247/5) and [in this fork](https://github.com/myselfhimself/SchrodingerWellPython).

I am just assisting hoping this will lead to interesting results.

**Comment by Reptorian1125** [comment]
This can be closed. Solved it.
